overrides:
  '@types/koa': 3.0.3
  '@types/minimatch': 5.1.2
  joi: 17.13.4
  js-yaml: 4.3.0
  picomatch: 2.3.2
  qs: 6.15.2
  tmp: 0.2.7
  uuid: 11.1.1

allowBuilds:
  '@midwayjs/cli': true
  '@swc/core': true
  unrs-resolver: true
